### ISSUE TITLE
Storing in Element tree fails with rss feed from freelancer fails when hits & character.

### ISSUE THREAD

**Issue by isaacegglestone** [isaacegglestone/KOA_data_collection_engine#1]
etroot = xml.etree.ElementTree.fromstring(sourcexml)

This above line in getsplitxml.py will often fail with an error message that says undefined element on line NNN column NNN

When I looked at the XML file I found that it contained &nstlne or something like that.

I'm guessing freelancer is putting browser HTML code in their webpage and the parser doesn't like that for some reason.

A couple different possible options I can think of.

1.) write our own split on <item> tag
or
2.)  Sanitise the input to filter out the &.

We should also confirm I'm storing the input correctly, perhaps I'm doing something too raw not sure.

**Comment by isaacegglestone** [comment]
As we switched to using feedparser I'm not sure this will be a problem anymore.
Lilkely it  was actually related to the fact I was setting the user-agent to Mozilla and the site was formatting the output for me in that case.  Not really sure. I'll leave the issue open in case someone runs into it again.

**Comment by tuux1598g** [comment]
Agree - this is no longer an issue. feedparser takes care of it and returns a json-style object anyway, so no need for xml parsing.

**Comment by isaacegglestone** [comment]
Okay closing the issue then. We can look at it later if we want to .
