### ISSUE TITLE
Vagrant file assumes Centos 7, but we have Amazon Linux and Debian to deal with as well.

### ISSUE THREAD

**Issue by isaacegglestone** [isaacegglestone/KOA_data_collection_engine#3]
Lukas's Box is Debian.

Mine is Amazon linux.

**Comment by tuux1598g** [comment]
It doesn't matter, Vagrant is designed to be run on your workstation
ideally, not the server/production.

We can choose any distro inside, the idea being simply to get a
production-like environment that is consistent for all of us - then you can
test your app inside it whilst developing. Hence we install things like
Mongo etc. to play with also.

If you prefer Debian, then its fine too - the guest OS doesn't matter,
other than to match it as best as possible to your target production
environment.


Kind Regards,

*Shaun Smith 施朗*
www.srsmith.co.uk <http://srsmith.co.uk/>

**Comment by isaacegglestone** [comment]
Vagrant will only be used on our workstations to faciltate development environments.

We still need a way to setup the production environment.
